### ISSUE TITLE
map LC fields to SF fields where possible

### ISSUE THREAD

**Issue by cgrayson** [activeprospect/leadconduit-integration-salesforce#1]
I found the list of Salesforce fields below by generating a new web-to-lead form and selecting all the possible fields, and Jonathan mapped them to standard LC fields where possible.

The integration should list the LC standard fields in `requestVariables`, and automatically map them to the right Salesforce fields. 

first_name - first_name
last_name - last_name
email - email
company - company.name
city - city
state - state
salutation ['Mr.', 'Ms.', 'Mrs.', 'Dr.', 'Prof.'] - _none_
title - title
url - website
phone - phone_1
mobile - phone_2
fax - _none_
street - address_1
zip - postal_code
country - country
description - comments (?)
lead_source ['Web', 'Phone Inquiry', 'Partner Referral', 'Purchased List', 'Other'] -  _none_
industry - company.industry
rating ['Hot', 'Warm', 'Cold'] -  _none_
revenue - company.monthly_sales (?)
employees -  _none_
Campaign_ID - reference
emailOptOut -  _none_
faxOptOut -  _none_
doNotCall -  _none_

**Comment by alexkwolfe** [comment]
I'm curious about their `Campaign_ID` field. Is this a hidden form field with a static value?
