### ISSUE TITLE
The leadconduit-fields module should be a devDependency

### ISSUE THREAD

**Issue by alexkwolfe** [activeprospect/leadconduit-integration-salesforce#12]
This module is only used in tests. Therefore it doesn't need to be installed at deploy time. Putting it in `devDependencies` will ensure that it's only installed when `npm install` is run without the `--production` argument.

https://github.com/activeprospect/leadconduit-integration-salesforce/blob/d636b0ffacdd18ff9b73c72edf2732b38f338f3d/package.json#L21

**Comment by jgrayson676** [comment]
fixed in pull request #13
